version: "3"
networks:
    laravel:

services:
  nginx1:
    image: nginx:stable-alpine
    container_name: laravel_nginx_1
    ports:
      - "8081:80"
    volumes:
      - "./serv1:/var/www/html"
      - "./serv1/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel

  nginx2:
    image: nginx:stable-alpine
    container_name: laravel_nginx_2
    ports:
      - "8082:80"
    volumes:
      - "./serv2:/var/www/html"
      - "./serv2/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - "3310:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    networks:
      - laravel
  
  php1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php_1
    ports:
      - "9000"
    volumes:
      - "./serv1:/var/www/html"
    networks:
      - laravel

  php2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php_2
    ports:
      - "9000"
    volumes:
      - "./serv2:/var/www/html"
    networks:
      - laravel
